//! Per-scenario field schema (1:1 from splash `item_fields()` / `blank_item()`).
//!
//! Used by the plan-view inline editor (C12) to render the right
//! number of TextInputs with the right labels per [`PlanKind`].

use serde::{Deserialize, Serialize};

use crate::enums::PlanKind;

/// One editable field on a plan item. `multi` means the user can
/// enter multiple lines (we render a taller TextInput); single-line
/// otherwise.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemField {
    pub key: String,
    pub label: String,
    pub multi: bool,
}

/// Per-kind field schema (1-6 fields). Default fallback is the
/// `{label, text}` shape used by `script` / `mindmap` / `quotes` /
/// `teardown` / default articles.
pub fn item_fields(kind: PlanKind) -> Vec<ItemField> {
    use PlanKind::*;
    let f = |k: &str, l: &str, m: bool| ItemField {
        key: k.to_string(),
        label: l.to_string(),
        multi: m,
    };
    match kind {
        Image => vec![
            f("heading", "段落标题", false),
            f("body", "正文", true),
            f("image_prompt", "生图 prompt", true),
        ],
        Video => vec![
            f("id", "镜号", false),
            f("duration_s", "时长(秒)", false),
            f("shot_type", "景别", false),
            f("description", "画面描述", true),
            f("voiceover", "配音文案", true),
            f("video_prompt", "生视频 prompt", true),
        ],
        Ppt => vec![
            f("kind", "类型 (cover/agenda/content/quote/end)", false),
            f("title", "页标题", false),
            f("bullets_text", "要点 (分号分隔)", false),
            f("notes", "讲稿", true),
            f("visual_prompt", "配图 prompt", true),
        ],
        Titles => vec![
            f("text", "标题", false),
            f("style_tag", "风格", false),
            f("score", "推荐指数 (1-100)", false),
        ],
        Xhs => vec![
            f("heading", "配图位", false),
            f("body", "生图 prompt", true),
        ],
        // Generic rows (script / mindmap / quotes / teardown / default)
        _ => vec![
            f("label", "标签", false),
            f("text", "内容", true),
        ],
    }
}

/// Initial empty row for a fresh item. `id` / `_k` defaults are
/// generated by the caller (so the editor can preserve the splash
/// "S1, S2, …" convention for video scenes).
pub fn blank_item(kind: PlanKind, next_id: u64) -> crate::PlanItem {
    use crate::PlanItem;
    use std::collections::BTreeMap;
    let mut fields = BTreeMap::new();
    for f in item_fields(kind) {
        let default = default_for(kind, &f.key, next_id);
        fields.insert(f.key, default);
    }
    PlanItem { k: next_id, fields }
}

fn default_for(kind: PlanKind, key: &str, next_id: u64) -> String {
    use PlanKind::*;
    match (kind, key) {
        (Video, "id") => format!("S{next_id}"),
        (Video, "duration_s") => "5".to_string(),
        (Video, "shot_type") => "中景".to_string(),
        (Titles, "text") => "新标题".to_string(),
        (Titles, "style_tag") => "通用".to_string(),
        (Titles, "score") => "80".to_string(),
        (Xhs, "heading") => "配图 prompt".to_string(),
        (Ppt, "kind") => "content".to_string(),
        (Ppt, "title") => "新页".to_string(),
        (Image, "heading") => "新段落".to_string(),
        // default rows (script / mindmap / quotes / teardown / None):
        (_, "label") => "新条目".to_string(),
        _ => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn image_has_3_fields_with_2_multi() {
        let f = item_fields(PlanKind::Image);
        assert_eq!(f.len(), 3);
        let multi = f.iter().filter(|x| x.multi).count();
        assert_eq!(multi, 2);
        assert_eq!(f[0].key, "heading");
        assert_eq!(f[1].key, "body");
        assert_eq!(f[2].key, "image_prompt");
    }

    #[test]
    fn video_has_6_fields() {
        let f = item_fields(PlanKind::Video);
        assert_eq!(f.len(), 6);
        let keys: Vec<&str> = f.iter().map(|x| x.key.as_str()).collect();
        assert_eq!(keys, vec!["id", "duration_s", "shot_type", "description", "voiceover", "video_prompt"]);
    }

    #[test]
    fn blank_video_seeds_id() {
        let it = blank_item(PlanKind::Video, 3);
        assert_eq!(it.k, 3);
        assert_eq!(it.get("id"), "S3");
        assert_eq!(it.get("duration_s"), "5");
        assert_eq!(it.get("shot_type"), "中景");
    }

    #[test]
    fn blank_titles_seeds_text_score() {
        let it = blank_item(PlanKind::Titles, 7);
        assert_eq!(it.get("text"), "新标题");
        assert_eq!(it.get("style_tag"), "通用");
        assert_eq!(it.get("score"), "80");
    }

    #[test]
    fn blank_default_uses_label_text() {
        // script / mindmap / quotes / teardown / None all fall back to label/text
        for k in [PlanKind::Script, PlanKind::Mindmap, PlanKind::Quotes, PlanKind::Teardown, PlanKind::None] {
            let it = blank_item(k, 1);
            assert!(!it.get("label").is_empty(), "{k:?} missing label");
            assert!(it.fields.contains_key("text"), "{k:?} missing text key");
        }
    }
}
